apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: nodejs-api
        image: lwpamihiranga.azurecr.io/backend:v1
        ports:
        - containerPort: 5000
        env:
          - name: DB_URL
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: DB_URL
