apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: reactjs-client
        image: lwpamihiranga.azurecr.io/frontend:v1
        ports:
        - containerPort: 3000
